// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12.04.2026, 21:39:55
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/pelac/Desktop/kam-pela/MakeSite/producktive/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/pelac/Desktop/kam-pela/MakeSite/producktive/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/pelac/Desktop/kam-pela/MakeSite/producktive/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/pelac/Desktop/kam-pela/MakeSite/producktive/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/pelac/Desktop/kam-pela/MakeSite/producktive/plugins/**/*.{js,ts,mjs}","C:/Users/pelac/Desktop/kam-pela/MakeSite/producktive/composables/**/*.{js,ts,mjs}","C:/Users/pelac/Desktop/kam-pela/MakeSite/producktive/utils/**/*.{js,ts,mjs}","C:/Users/pelac/Desktop/kam-pela/MakeSite/producktive/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/pelac/Desktop/kam-pela/MakeSite/producktive/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/pelac/Desktop/kam-pela/MakeSite/producktive/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/pelac/Desktop/kam-pela/MakeSite/producktive/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;